[project]
name = "00-python-to-native"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cython>=3.2.4",
    "mypy>=1.19.1",
    "numba>=0.63.1",
    "setuptools>=82.0.0",
]
